// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

//包名，通过protoc生成时go文件时

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Login struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type BeatHart struct {
	OnlineTime           int64    `protobuf:"varint,1,opt,name=OnlineTime,proto3" json:"OnlineTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeatHart) Reset()         { *m = BeatHart{} }
func (m *BeatHart) String() string { return proto.CompactTextString(m) }
func (*BeatHart) ProtoMessage()    {}
func (*BeatHart) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *BeatHart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeatHart.Unmarshal(m, b)
}
func (m *BeatHart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeatHart.Marshal(b, m, deterministic)
}
func (m *BeatHart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeatHart.Merge(m, src)
}
func (m *BeatHart) XXX_Size() int {
	return xxx_messageInfo_BeatHart.Size(m)
}
func (m *BeatHart) XXX_DiscardUnknown() {
	xxx_messageInfo_BeatHart.DiscardUnknown(m)
}

var xxx_messageInfo_BeatHart proto.InternalMessageInfo

func (m *BeatHart) GetOnlineTime() int64 {
	if m != nil {
		return m.OnlineTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Login)(nil), "login.Login")
	proto.RegisterType((*BeatHart)(nil), "login.BeatHart")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x24, 0xb9, 0x58, 0x7d,
	0x40, 0x0c, 0x21, 0x01, 0x2e, 0xe6, 0x80, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x10, 0x53, 0x49, 0x8b, 0x8b, 0xc3, 0x29, 0x35, 0xb1, 0xc4, 0x23, 0xb1, 0xa8, 0x44, 0x48, 0x8e,
	0x8b, 0xcb, 0x3f, 0x2f, 0x27, 0x33, 0x2f, 0x35, 0x24, 0x33, 0x37, 0x15, 0xac, 0x88, 0x39, 0x08,
	0x49, 0x24, 0x89, 0x0d, 0x6c, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xdc, 0x0f, 0x24,
	0x63, 0x00, 0x00, 0x00,
}
